apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 851512651356.dkr.ecr.us-east-1.amazonaws.com/frontend:1.0.3
  imagePullSecrets:
    - name: aws-ecr


---
apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
   - name: backend
     image: 851512651356.dkr.ecr.us-east-1.amazonaws.com/backend:2.0.1
  imagePullSecrets:
    - name: aws-ecr

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
